services:
  wolf-bank-app:
    build: .
    container_name: wolf-bank-app
    environment:
      API_URL: ${API_URL}
      MONGO_URL: ${MONGO_URL}
      VITE_FIREBASE_VAPID_KEY: ${VITE_FIREBASE_VAPID_KEY}
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
    env_file:
      - .env.docker
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - wolf-bank-mongo
    networks:
      - wolf-bank-network

  wolf-bank-mongo:
    image: mongo:4
    container_name: wolf-bank-mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - wolf-bank-network

networks:
  wolf-bank-network:
    driver: bridge
